export const currencySymbols: Record<string, string> = {
  USD: "$",
  USN: "$",
  USS: "$",
  EUR: "€",
  GBP: "£",
  JPY: "¥",
  CNY: "¥",
  HKD: "HK$",
  TWD: "NT$",
  KRW: "₩",
  INR: "₹",
  RUB: "₽",
  UAH: "₴",
  BYN: "Br",
  KZT: "₸",
  AZN: "₼",
  GEL: "₾",
  TRY: "₺",
  ILS: "₪",
  AED: "د.إ",
  SAR: "ر.س",
  QAR: "ر.ق",
  KWD: "د.ك",
  BHD: "ب.د",
  OMR: "ر.ع.",
  EGP: "ج.م",
  MAD: "د.م.",
  TND: "د.ت",
  DZD: "DA",
  ZAR: "R",
  NGN: "₦",
  GHS: "₵",
  KES: "KSh",
  XOF: "CFA",
  XAF: "FCFA",
  XPF: "₣",
  AUD: "A$",
  NZD: "NZ$",
  CAD: "C$",
  SGD: "S$",
  MYR: "RM",
  THB: "฿",
  PHP: "₱",
  IDR: "Rp",
  VND: "₫",
  PKR: "Rs",
  BDT: "৳",
  LKR: "Rs",
  NPR: "Rs",
  MUR: "Rs",
  BND: "B$",
  BRL: "R$",
  MXN: "MX$",
  ARS: "AR$",
  CLP: "CLP$",
  COP: "COL$",
  PEN: "S/",
  UYU: "$U",
  PYG: "₲",
  BOB: "Bs",
  CRC: "₡",
  DOP: "RD$",
  GTQ: "Q",
  HNL: "L",
  NIO: "C$",
  JMD: "J$",
  TTD: "TT$",
  BBD: "Bds$",
  BZD: "BZ$",
  BSD: "$",
  KYD: "CI$",
  BMD: "$",
  CHF: "CHF",
  SEK: "kr",
  NOK: "kr",
  DKK: "kr",
  ISK: "kr",
  PLN: "zł",
  CZK: "Kč",
  HUF: "Ft",
  RON: "lei",
  BGN: "лв",
  RSD: "дин",
  MKD: "ден",
  BAM: "KM",
  HRK: "kn",
  ALL: "L",
  AMD: "֏",
  KGS: "с",
  UZS: "so'm",
  TJS: "SM",
  MNT: "₮",
  LAK: "₭",
  KHR: "៛",
  MMK: "K",
  IRR: "﷼",
  IQD: "ع.د",
  JOD: "د.ا",
  LBP: "ل.ل",
  SYP: "£S",
  YER: "﷼",
  ETB: "Br",
  TZS: "TSh",
  UGX: "USh",
  AOA: "Kz",
  MZN: "MT",
  ZMW: "ZK",
};

export function formatAmount(n: number, code?: string): string {
  const num = new Intl.NumberFormat().format(n);
  if (!code) return num;
  const up = code.toUpperCase();
  const sym = currencySymbols[up] ?? up;
  const needsSpace = /^[A-Za-z]{2,}$/.test(sym);
  return `${sym}${needsSpace ? " " : ""}${num}`;
}
