// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StockDataAggregator.Persistence;

#nullable disable

namespace StockDataAggregator.Persistence.Migrations
{
    [DbContext(typeof(FinanceContext))]
    partial class FinanceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StockDataAggregator.Persistence.Entities.FinancialsYearly", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Earnings")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Revenue")
                        .HasColumnType("numeric");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Symbol", "Year")
                        .IsUnique();

                    b.ToTable("FinancialsYearly");
                });

            modelBuilder.Entity("StockDataAggregator.Persistence.Entities.SymbolMetrics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<decimal>("DebtToEquity")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("DividendYield")
                        .HasColumnType("numeric");

                    b.Property<decimal>("EsgEnvironment")
                        .HasColumnType("numeric");

                    b.Property<decimal>("EsgGovernance")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("EsgPublicationDate")
                        .HasColumnType("date");

                    b.Property<decimal>("EsgSocial")
                        .HasColumnType("numeric");

                    b.Property<decimal>("EsgTotal")
                        .HasColumnType("numeric");

                    b.Property<decimal>("FourYearEarningsGrowth")
                        .HasColumnType("numeric");

                    b.Property<decimal>("FourYearSalesGrowth")
                        .HasColumnType("numeric");

                    b.Property<decimal>("FreeCashFlow")
                        .HasColumnType("numeric");

                    b.Property<decimal>("OneYearSalesGrowth")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PegRatio")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ReturnOnEquity")
                        .HasColumnType("numeric");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("SymbolMetrics");
                });

            modelBuilder.Entity("StockDataAggregator.Persistence.Entities.TrackedSymbol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.ToTable("TrackedSymbols");
                });
#pragma warning restore 612, 618
        }
    }
}
